import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Product = { id: string; name: string; description: string; price: number; stockQuantity: number }
type CartLine = Product & { quantity: number }
type Order = { id: string; total: number; createdUtc: string; status: string }
const apiUrl = import.meta.env.VITE_API_URL ?? 'http://localhost:5016/api'

function go(path: string) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
function Header({ cartCount, user }: { cartCount: number; user: string | null }) { return <header><button className="brand-button" onClick={() => go('/')}>Northwind Market</button><nav><button onClick={() => go('/')}>Shop</button><button onClick={() => go('/orders')}>Orders</button><button onClick={() => go('/admin')}>Admin</button><button onClick={() => go(user ? '/account' : '/login')}>{user ?? 'Sign in'}</button><button className="cart-link" onClick={() => go('/cart')}>Cart ({cartCount})</button></nav></header> }
function Layout({ children, cart, user }: { children: React.ReactNode; cart: CartLine[]; user: string | null }) { return <main><Header cartCount={cart.reduce((sum, x) => sum + x.quantity, 0)} user={user} />{children}<footer>Northwind Market · Built with ASP.NET Core, React, and SQL Server</footer></main> }
function Catalog({ products, add }: { products: Product[]; add: (p: Product) => void }) { return <><section className="hero"><small>CURATED GOODS / 2026</small><h1>Everyday essentials,<br /><em>beautifully considered.</em></h1><p>Discover products selected for quality, utility, and a little bit of joy.</p></section><section><div className="heading"><h2>Featured products</h2><span>{products.length} items</span></div><div className="grid">{products.map(p => <article className="card" key={p.id}><div className="image">✦</div><div className="card-content"><h3>{p.name}</h3><p>{p.description}</p><strong>${p.price.toFixed(2)}</strong><button onClick={() => add(p)} disabled={!p.stockQuantity}>Add to cart</button><button className="text-button" onClick={() => go(`/products/${p.id}`)}>Details</button></div></article>)}</div></section></> }
function ProductDetails({ product, add }: { product?: Product; add: (p: Product) => void }) { if (!product) return <NotFound />; return <section className="page"><button className="text-button" onClick={() => go('/')}>← Back to shop</button><div className="detail"><div className="image large">✦</div><div><small>FEATURED PRODUCT</small><h1>{product.name}</h1><p>{product.description}</p><h2>${product.price.toFixed(2)}</h2><p>{product.stockQuantity} available</p><button onClick={() => add(product)}>Add to cart</button></div></div></section> }
function Cart({ cart, remove }: { cart: CartLine[]; remove: (id: string) => void }) { const total = cart.reduce((sum, x) => sum + x.price * x.quantity, 0); return <section className="page"><h1>Your cart</h1>{cart.length === 0 ? <p>Your cart is empty. <button className="text-button" onClick={() => go('/')}>Continue shopping</button></p> : <><div className="cart-list">{cart.map(x => <div className="cart-row" key={x.id}><span><b>{x.name}</b><small>Qty {x.quantity}</small></span><strong>${(x.price * x.quantity).toFixed(2)}</strong><button onClick={() => remove(x.id)}>Remove</button></div>)}</div><div className="summary"><h2>Total ${total.toFixed(2)}</h2><button onClick={() => go('/checkout')}>Checkout</button></div></>}</section> }
function Checkout({ cart, complete }: { cart: CartLine[]; complete: () => void }) { const submit = (event: FormEvent) => { event.preventDefault(); complete() }; return <section className="page narrow"><h1>Checkout</h1><form onSubmit={submit}><label>Full name<input required /></label><label>Shipping address<input required /></label><label>Card number<input required inputMode="numeric" placeholder="4242 4242 4242 4242" /></label><button disabled={!cart.length}>Place order</button></form></section> }
function Orders({ orders }: { orders: Order[] }) { return <section className="page"><h1>Order history</h1>{orders.length ? orders.map(o => <div className="order-row" key={o.id}><span><b>Order #{o.id.slice(0, 8)}</b><small>{new Date(o.createdUtc).toLocaleDateString()}</small></span><strong>${o.total.toFixed(2)}</strong><span className="badge">{o.status}</span></div>) : <p>No orders yet.</p>}</section> }
function Login({ signIn }: { signIn: (email: string, password: string) => Promise<void> }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await signIn(data.get('email') as string, data.get('password') as string) }; return <section className="page narrow"><h1>Welcome back</h1><form onSubmit={submit}><label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><label>Password<input name="password" type="password" required /></label><button>Sign in</button><button type="button" className="secondary" onClick={() => go('/register')}>Create account</button></form></section> }
function Register({ register }: { register: (name: string, email: string, password: string) => Promise<void> }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await register(data.get('name') as string, data.get('email') as string, data.get('password') as string) }; return <section className="page narrow"><h1>Create account</h1><form onSubmit={submit}><label>Name<input name="name" required /></label><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" required /></label><button>Create account</button></form></section> }
function Admin() { return <section className="page"><div className="heading"><h1>Admin dashboard</h1><button onClick={() => go('/admin/products')}>Manage products</button></div><div className="metrics"><div><b>128</b><small>Orders this month</small></div><div><b>$12,480</b><small>Revenue</small></div><div><b>24</b><small>Low stock items</small></div></div></section> }
function AdminProducts({ products }: { products: Product[] }) { return <section className="page"><div className="heading"><h1>Product management</h1><button onClick={() => alert('Product creation API can be connected here.')}>Add product</button></div>{products.map(p => <div className="order-row" key={p.id}><span><b>{p.name}</b><small>{p.stockQuantity} in stock</small></span><strong>${p.price.toFixed(2)}</strong><button>Edit</button></div>)}</section> }
function NotFound() { return <section className="page centered"><h1>Page not found</h1><p>That page does not exist.</p><button onClick={() => go('/')}>Return home</button></section> }

export default function App() {
  const [path, setPath] = useState(window.location.pathname); const [products, setProducts] = useState<Product[]>([]); const [cart, setCart] = useState<CartLine[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [user, setUser] = useState<string | null>(null); const [token, setToken] = useState<string | null>(() => localStorage.getItem('ecommerce_token'))
  useEffect(() => { const onPop = () => setPath(window.location.pathname); window.addEventListener('popstate', onPop); fetch(`${apiUrl}/products`).then(r => r.ok ? r.json() : Promise.reject()).then(setProducts).catch(() => setProducts([])); return () => window.removeEventListener('popstate', onPop) }, [])
  const add = (product: Product) => setCart(current => { const found = current.find(x => x.id === product.id); return found ? current.map(x => x.id === product.id ? { ...x, quantity: x.quantity + 1 } : x) : [...current, { ...product, quantity: 1 }] })
  const complete = () => { const total = cart.reduce((sum, x) => sum + x.price * x.quantity, 0); setOrders(current => [{ id: crypto.randomUUID(), total, createdUtc: new Date().toISOString(), status: 'Pending' }, ...current]); setCart([]); go('/orders') }
  const authenticate = async (endpoint: string, body: object) => { const response = await fetch(`${apiUrl}/auth/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error('Authentication failed'); const result = await response.json(); localStorage.setItem('ecommerce_token', result.token); setToken(result.token); setUser(result.user.email); go('/account') }
  const productId = path.split('/')[2]; const product = products.find(x => x.id === productId); let page: React.ReactNode
  if (path === '/') page = <Catalog products={products} add={add} />; else if (path.startsWith('/products/')) page = <ProductDetails product={product} add={add} />; else if (path === '/cart') page = <Cart cart={cart} remove={id => setCart(cart.filter(x => x.id !== id))} />; else if (path === '/checkout') page = <Checkout cart={cart} complete={complete} />; else if (path === '/orders') page = <Orders orders={orders} />
  else if (path === '/login') page = <Login signIn={(email, password) => authenticate('login', { email, password })} />; else if (path === '/register') page = <Register register={(displayName, email, password) => authenticate('register', { displayName, email, password })} />; else if (path === '/account') page = <section className="page"><h1>Account</h1><p>Signed in as {user}</p><p>{token ? 'Authenticated with the API.' : 'Not authenticated.'}</p><button onClick={() => { localStorage.removeItem('ecommerce_token'); setToken(null); setUser(null); go('/') }}>Sign out</button></section>; else if (path === '/admin') page = <Admin />; else if (path === '/admin/products') page = <AdminProducts products={products} />; else page = <NotFound />
  return <Layout cart={cart} user={user}>{page}</Layout>
}


